### ISSUE TITLE
Skeleton Stuck

### ISSUE THREAD

**Issue by erikji** [maitian352/Meadow-Guarder-old2#366]
Gets Stuck

https://user-images.githubusercontent.com/87676483/167302857-9f8863b3-97ba-4102-99b5-47407e4c786a.mp4

Rickroll below:
<a href="https://meadowguarder.herokuapp.com/client/websiteAssets/Never%20Gonna%20Give%20You%20Up.mp4"> https://discord.com/app</a>

**Comment by Suvanth-Erranki** [comment]
We already have seen this before.

**Comment by Suvanth-Erranki** [comment]
It is only stuck while you are in that position.

**Comment by erikji** [comment]
but i died 😭

**Comment by definitely-nobody-is-here** [comment]
mountain guarder issues go brrrr
