### ISSUE TITLE
It won't let me play.

### ISSUE THREAD

**Issue by BannanaPants** [maitian352/Meadow-Guarder-old2#372]
It says application error whenever I load it.
![Screenshot 2022-06-01 12 18 34 PM](https://user-images.githubusercontent.com/95425042/171452247-03af4c57-6b88-4256-895f-612e6b2ccb0c.png)

**Comment by definitely-nobody-is-here** [comment]
That's not the game not letting you play, that's the game crashing.

**Comment by BannanaPants** [comment]
Oh, Thanks.
