### ISSUE TITLE
Add a mine.

### ISSUE THREAD

**Issue by BannanaPants** [maitian352/Meadow-Guarder-old2#373]
You know that miner shack area on the forest island, you should make it so in the future you could go there and mine ore. this would be really helpful because then you would have to kill a ton of mobs just to get 5 diamonds. You could make it so you use the pickaxes to mine the ore. The better the pick is the faster it mines up. You could also make it so the better the ore is the better the harder it is to find. You could also add a boss in the mine like a mole or something.

**Comment by definitely-nobody-is-here** [comment]
Too bad he's too busy working on Ocean Guarder.

**Comment by maitian352** [comment]
meadow guarde dead
