### ISSUE TITLE
Uhhh......... is this a game glitch????

### ISSUE THREAD

**Issue by BannanaPants** [maitian352/Meadow-Guarder-old2#374]

**Comment by BannanaPants** [comment]
![Screenshot 2022-06-01 1 20 15 PM](https://user-images.githubusercontent.com/95425042/171465465-6e3dbe6c-d097-493a-97ed-9c19b0c73923.png)
![Screenshot 2022-06-01 1 19 59 PM](https://user-images.githubusercontent.com/95425042/171465466-1e678643-c656-4415-87bb-7be00c5ddca5.png)

**Comment by definitely-nobody-is-here** [comment]
When sp expands the map but forgets to complete the trees and terrain that were cut off before. It's a map making error.

**Comment by erikji** [comment]
See issue #357
